TimeTracker/ViewModels/CloseTimeLog.cs
using NodaTime;

namespace TimeTracker.ViewModels
{
    public class CloseTimeLog
    {
        public int TimeLogId { get; set; }
        public LocalTime EndTime { get; set; }
    }
}

TimeTracker/ViewModels/FullCustomForm.cs
using NodaTime;

namespace TimeTracker.ViewModels
{
    public class FullCustomForm
    {
        public LocalDate Date { get; set; }
        public LocalTime StartTime { get; set; }
        public LocalTime EndTime { get; set; }
    }
}

TimeTracker/Controllers/AuthenticationController.cs
using System;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using DotNetOpenAuth.Messaging;
using DotNetOpenAuth.OpenId;
using DotNetOpenAuth.OpenId.Extensions.AttributeExchange;
using DotNetOpenAuth.OpenId.RelyingParty;
using TimeTracker.Models;

namespace TimeTracker.Controllers
{
    public class AuthenticationController : DocumentController
    {
        private void LoginUser(User user)
        {
            string userData = user.Serialize();

            var authenticationTicket = new FormsAuthenticationTicket(
                1,
                user.Email,
                DateTime.Now,
                DateTime.Now.AddMinutes(15),
                false,
                userData);

            string ticket = FormsAuthentication.Encrypt(authenticationTicket);
            var formsCookie = new HttpCookie(FormsAuthentication.FormsCookieName, ticket);
            Response.Cookies.Add(formsCookie);
        }


        public ActionResult LogOn()
        {
            var openid = new OpenIdRelyingParty();
            IAuthenticationResponse response = openid.GetResponse();


            if (response != null)
            {
                var fetchResponse = response.GetExtension<FetchResponse>();
                switch (response.Status)
                {
                    case AuthenticationStatus.Authenticated:
                        var claimedIdentifier = response.ClaimedIdentifier;

                        User user = DocumentSession.Query<User>("UserByClaimedIdentifier").SingleOrDefault(u => u.ClaimedIdentifier.Equals(claimedIdentifier));

                        if (user == null)
                        {
                            user = new User
                                       {
                                           FullName = fetchResponse.GetAttributeValue(WellKnownAttributes.Name.FullName),
                                           Email = fetchResponse.GetAttributeValue(WellKnownAttributes.Contact.Email),
                                           ClaimedIdentifier = claimedIdentifier
                                       };

                            DocumentSession.Store(user);
                        }
                        
                        LoginUser(user);

                        if (string.IsNullOrEmpty(user.FullName))
                        {
                            return RedirectToAction("Details", "User");
                        }

                        return RedirectToAction("Index", "Home");

                    case AuthenticationStatus.Canceled:
                        ModelState.AddModelError("loginIdentifier",
                                                 "Login was cancelled at the provider");
                        break;
                    case AuthenticationStatus.Failed:
                        ModelState.AddModelError("loginIdentifier",
                                                 "Login failed using the provided OpenID identifier");
                        break;
                }
            }

            return View();
        }

        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult LogOn(string loginIdentifier)
        {
            if (!Identifier.IsValid(loginIdentifier))
            {
                ModelState.AddModelError("loginIdentifier",
                                         "The specified login identifier is invalid");
                return View();
            }
            else
            {
                var openid = new OpenIdRelyingParty();
                IAuthenticationRequest request = openid.CreateRequest(Identifier.Parse(loginIdentifier));
                
                /*
                request.AddExtension(new ClaimsRequest
                                         {
                                             Email = DemandLevel.Require,
                                             FullName = DemandLevel.Require§
                                         });
                */

                var fetch = new FetchRequest();
                fetch.Attributes.AddRequired(WellKnownAttributes.Contact.Email);
                fetch.Attributes.AddRequired(WellKnownAttributes.Name.FullName);
                request.AddExtension(fetch);

                return request.RedirectingResponse.AsActionResult();
            }
        }

        public ActionResult Logout()
        {
            FormsAuthentication.SignOut();
            return Redirect("/");
        }
    }
}

TimeTracker/Controllers/HomeController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using NodaTime;
using TimeTracker.Models;
using TimeTracker.ViewModels;

namespace TimeTracker.Controllers
{
    public class IndexViewModel
    {
        public IOrderedQueryable<TimeLog> Logs { get; set; }

        public FullCustomForm Form { get; set; }
    }

    public class HomeController : DocumentController
    {
        private readonly IClock clock;

        public HomeController(IClock clock)
        {
            this.clock = clock;
        }

        public ActionResult Index()
        {
            if (!User.Identity.IsAuthenticated)
            {
                return View("StartPage");
            }

            var logs =
                DocumentSession.Query<TimeLog>()
                               .Where(x => (x.UserId == Principal.Id)).OrderByDescending(z=>z.StartTime);

            var zonedDateTime = new ZonedDateTime(clock.Now, CurrentTimeZone);
            var localDate = TempData["prev-date"] is LocalDate ? (LocalDate)TempData["prev-date"] : zonedDateTime.LocalDateTime.Date;

            return View(new IndexViewModel
                            {
                                Logs = logs,
                                Form = new FullCustomForm() {Date = localDate}
                            });
        }

        
        [HttpPost]
        [Authorize]
        public ActionResult FullCustom(FullCustomForm fullCustomForm)
        {
            var fullCustomFormTimeLogConverter = new FullCustomFormTimeLogConverter(clock);

            var timeLog = fullCustomFormTimeLogConverter.Convert(fullCustomForm);
            timeLog.UserId = Principal.Id;

            DocumentSession.Store(timeLog);

            TempData["prev-date"] = fullCustomForm.Date;

            return RedirectToAction("Index");
        }

        [HttpPost]
        [Authorize]
        public ActionResult CloseTimeLog(CloseTimeLog closeTimeLog)
        {
            var timeLog = DocumentSession.Load<TimeLog>(closeTimeLog.TimeLogId);

            if (timeLog.UserId != Principal.Id)
            {
                throw new Exception("It's not possible to delete another users timelog...");
            }

            var duration = Duration(closeTimeLog, timeLog.StartTime);

            timeLog.Duration = duration;

            DocumentSession.Store(timeLog);

            return RedirectToAction("Index");
        }

        private TimeSpan Duration(CloseTimeLog closeTimeLog, DateTimeOffset timeLog)
        {
            var fromDateTimeOffset = ZonedDateTime.FromDateTimeOffset(timeLog);
            var localTime = closeTimeLog.EndTime;
            
            if (localTime.Equals(LocalTime.Midnight))
            {
                var zonedDateTime = new ZonedDateTime(clock.Now, CurrentTimeZone);
                localTime = zonedDateTime.LocalDateTime.TimeOfDay;
            }

            var between = Period.Between(fromDateTimeOffset.LocalDateTime.TimeOfDay, localTime);
            var duration = between.ToDuration().ToTimeSpan();
            return duration;
        }

        [HttpPost]
        [Authorize]
        public ActionResult Delete(int id)
        {
            var timeLog = DocumentSession.Load<TimeLog>(id);

            if (timeLog.UserId != Principal.Id)
            {
                throw new Exception("It's not possible to delete another users timelog...");
            }

            DocumentSession.Delete(timeLog);

            return RedirectToAction("Index");
        }
    }
}

TimeTracker/Views/Home/CloseTimeLogForm.cshtml
@model TimeTracker.ViewModels.CloseTimeLog

@using (Html.BeginForm("CloseTimeLog", "Home", FormMethod.Post, new { @class = "form-inline" }))
{
    <fieldset>
        <legend>Close timelog</legend>
        @Html.HiddenFor(m => m.TimeLogId)

        @Html.LabelFor(m => m.EndTime)
        @Html.TextBoxFor(model => model.EndTime, new {@Value = string.Empty, @placeholder = "1700"})
    </fieldset>    

    <button type="submit" class="btn">Close log</button>
}

TimeTracker/Views/Home/FullCustom.cshtml
@model TimeTracker.ViewModels.FullCustomForm

@using (Html.BeginForm("FullCustom", "Home", FormMethod.Post, new {@class = "form-inline"}))
{
    @Html.TextBoxFor(model => model.StartDate, new {@Value = DateTime.Now.Date.ToShortDateString()})

    @Html.TextBoxFor(model => model.StartTime, new {@Value = string.Empty, @placeholder = "0900"})

    @Html.TextBoxFor(model => model.EndTime, new {@Value = string.Empty, @placeholder = "1700"})

    <button type="submit" class="btn">Add work</button>
}

TimeTracker/Views/Home/FullCustomForm.cshtml
@using System.Globalization
@model TimeTracker.ViewModels.FullCustomForm

@using (Html.BeginForm("FullCustom", "Home", FormMethod.Post))
{
    <fieldset>
        <legend>Submit some work</legend>
        @Html.LabelFor(m => m.Date)
        @Html.TextBoxFor(model => model.Date, new {@Value = Model.Date.ToString("yyyy-MM-dd", CultureInfo.InvariantCulture), @class = "date-picker", @autofocus="autofocus"})

    
        @Html.LabelFor(m => m.StartTime)
        @Html.TextBoxFor(model => model.StartTime, new {@Value = string.Empty, @placeholder = "0900"})

        @Html.LabelFor(m => m.EndTime)
        @Html.TextBoxFor(model => model.EndTime, new {@Value = string.Empty, @placeholder = "1700"})
    </fieldset>    

    <button type="submit" class="btn">Add work</button>
}

TimeTracker/Views/Home/Index.cshtml
@using TimeTracker.Models
@using TimeTracker.ViewModels
@model TimeTracker.Controllers.IndexViewModel
@{
    ViewBag.Title = "Index";
}

<h1>Time time time</h1>
@Html.Partial("FullCustomForm", Model.Form)

@foreach (TimeLog m in Model.Logs)
{
    <div class="well">
        <strong>@m.StartTime.Date.ToShortDateString()</strong><br />


        @if (m.IsOpen())
        {
            @m.StartTime.TimeOfDay<i class="icon-chevron-right"></i>
            @m.Duration.TotalHours.ToString("N1")
            @Html.Partial("CloseTimeLogForm", new CloseTimeLog {TimeLogId = m.Id})
        }
        else
        {
            @m.StartTime.TimeOfDay<i class="icon-chevron-right"></i>
            @m.StartTime.TimeOfDay.Add(m.Duration)<i class="icon-chevron-right"></i>
            @m.Duration.TotalHours.ToString("N1")
        }

        @using (Html.BeginForm("Delete", "Home", new {id = m.Id}, FormMethod.Post))
        {
            <button class="close"><i class="icon-trash"></i></button>
        }
    </div>
}

TimeTracker/Views/Home/StartPage.cshtml
@model dynamic

@{
    ViewBag.Title = "Getting started";
}

<div class="hero-unit">
    <h1>TimeTracker</h1>
    <p>Easy to use time tracker, give it a try!</p>
    <p>
        @using (Html.BeginForm("LogOn", "Authentication", FormMethod.Post, new { @id = "openIdForm" }))
        {
            @Html.Hidden("loginIdentifier", "https://www.google.com/accounts/o8/id")
            <button class="btn btn-primary btn-large">Login with your google account</button>
        }
    </p>
</div>

<div class="alert alert-success">
    Missing a feature, found a bug or just looking for the <a href="https://github.com/orjan/time-tracker">source</a>?
</div>